CREATE TABLE IF NOT EXISTS `mybb_ajaxchat` (
  `uid` int(10) NOT NULL,
  `date` int(10) NOT NULL,
  `message` varchar(300) CHARACTER SET utf8 NOT NULL,
  `id` int(10) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=15191 ;
